apiVersion: apps/v1
kind: Deployment
metadata:
  name: minifleet-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minifleet-web-app
  template:
    metadata:
      labels:
        app: minifleet-web-app
    spec:
      containers:
      - name: minifleet-web-app
        image: gcr.io/extreme-torch-424713-g5/minifleet-web-app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "5m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minifleet-web-app-service
spec:
  type: NodePort
  selector:
    app: minifleet-web-app
  ports:
  - name: http
    protocol: TCP
    port: 60001
    targetPort: 80
    
    